from __future__ import annotations

import uuid
from pathlib import Path
from unittest.mock import Mock, patch

from fastapi.testclient import TestClient

from app.api.dependencies import execution_adapter_dependency
from app.config import Settings
from app.main import app
from app.models.agent import Agent
from app.models.common import AgentRole, TaskType
from app.services.execution import CodexCLIExecutionAdapter, ExecutionResult
from app.services.agent_catalog import default_template_id_for_role
from app.services.task_routing import preferred_role_for_task


class FakeExecutionAdapter:
    def __init__(
        self,
        *,
        stdout: str,
        stderr: str = "",
        exit_code: int = 0,
        files_to_create: list[str] | None = None,
    ):
        self._result = ExecutionResult(
            stdout=stdout,
            stderr=stderr,
            exit_code=exit_code,
            command=["fake-executor"],
        )
        self.prompts: list[str] = []
        self.workdirs: list[str | None] = []
        self._files_to_create = files_to_create or []

    def run(
        self,
        *,
        prompt: str,
        workdir: Path | None = None,
        on_output=None,
    ) -> ExecutionResult:
        self.prompts.append(prompt)
        self.workdirs.append(str(workdir) if workdir is not None else None)
        if on_output is not None:
            if self._result.stderr:
                on_output("stderr", self._result.stderr)
            if self._result.stdout:
                on_output("stdout", self._result.stdout)
        if workdir is not None:
            for relative_path in self._files_to_create:
                target = workdir / relative_path
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text("generated by fake executor\n")
        return self._result


class FakeExplodingExecutionAdapter:
    def __init__(self, *, message: str = "boom") -> None:
        self._message = message

    def run(self, *, prompt: str, workdir: Path | None = None, on_output=None) -> ExecutionResult:
        raise RuntimeError(self._message)


def test_codex_cli_adapter_reports_missing_binary() -> None:
    adapter = CodexCLIExecutionAdapter(
        settings=Settings(codex_cli_command="definitely-missing-codex-binary")
    )

    result = adapter.run(prompt="test prompt")

    assert result.exit_code == 127
    assert "CODEX_EXECUTION_BACKEND=mock" in result.stderr


def test_codex_cli_adapter_uses_explicit_approval_and_sandbox_flags() -> None:
    adapter = CodexCLIExecutionAdapter(settings=Settings())
    process = Mock()
    process.stdout = Mock()
    process.stderr = Mock()
    process.stdout.readline = Mock(side_effect=['{"summary":"ok","follow_up_tasks":[]}', ""])
    process.stderr.readline = Mock(side_effect=[""])
    process.wait = Mock(return_value=0)
    selector_instance = Mock()
    selector_instance.get_map = Mock(side_effect=[{"stdout": object()}, {}])
    selector_instance.select = Mock(
        return_value=[(Mock(fileobj=process.stdout, data=("stdout", [])), None)]
    )
    selector_instance.unregister = Mock()

    with patch("app.services.execution.subprocess.Popen", return_value=process) as popen_mock, patch(
        "app.services.execution.selectors.DefaultSelector",
        return_value=selector_instance,
    ):
        result = adapter.run(prompt="return ok", workdir=Path("/workspace/projects/future_calc"))

    assert result.exit_code == 0
    command = popen_mock.call_args.args[0]
    assert command[:7] == ["codex", "-a", "never", "exec", "-s", "danger-full-access", "-C"]
    assert "--full-auto" not in command


def test_task_routing_prefers_specialized_roles() -> None:
    assert preferred_role_for_task(
        title="Build calculator shell",
        description="Implement the initial app shell.",
        task_type=TaskType.FEATURE,
    ) == AgentRole.DEVELOPER
    assert preferred_role_for_task(
        title="Establish visual direction and motion rules",
        description="Set the visual design direction and animation rules.",
        task_type=TaskType.FEATURE,
    ) == AgentRole.DESIGNER
    assert preferred_role_for_task(
        title="Define spectacle-first product scope",
        description="Lock the feature envelope and explicit exclusions.",
        task_type=TaskType.RESEARCH,
    ) == AgentRole.ARCHITECT
    assert preferred_role_for_task(
        title="Implement calculator logic and input handling",
        description="Wire the standard calculation engine to UI controls and keyboard shortcuts.",
        task_type=TaskType.FEATURE,
    ) == AgentRole.DEVELOPER
    assert preferred_role_for_task(
        title="Layer in high-impact visual effects and animations",
        description="Add the over-the-top presentation layer without breaking usability.",
        task_type=TaskType.FEATURE,
    ) == AgentRole.DEVELOPER


def test_run_agent_once_completes_task_and_creates_follow_ups(client: TestClient, projects_root) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "platform", "name": "Platform", "description": "Shared platform work."},
    )
    adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Implemented the first worker pass.",'
            '"memory_summary":"Worker completed feature",'
            '"memory_content":"Feature implementation landed and needs review.",'
            '"artifact_paths":["deliverables/implementation.md"],'
            '"follow_up_tasks":[{"title":"Review implementation",'
            '"description":"Perform a focused code review.",'
            '"type":"review","project_id":"platform"}]}'
        ),
        files_to_create=["deliverables/implementation.md"],
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent = client.post("/api/v1/agents", json={"name": "worker-dev", "role": "developer"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Ship worker runtime",
            "description": "Implement the first worker cycle.",
            "type": "feature",
            "project_id": "platform",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "completed"
    assert payload["task_id"] == task["id"]
    assert len(payload["follow_up_task_ids"]) == 1
    assert payload["task_run"]["status"] == "succeeded"
    assert payload["task_run"]["created_follow_up_tasks"] == 1

    task_response = client.get("/api/v1/tasks")
    tasks = task_response.json()
    assert {item["status"] for item in tasks} == {"done", "todo"}

    memory_response = client.get("/api/v1/memory")
    memories = memory_response.json()
    assert len(memories) == 1
    assert memories[0]["summary"] == "Worker completed feature"

    task_runs_response = client.get("/api/v1/task-runs")
    task_runs = task_runs_response.json()
    assert len(task_runs) == 1
    assert task_runs[0]["task_id"] == task["id"]
    assert adapter.prompts
    assert adapter.workdirs[0] is not None
    assert adapter.workdirs[0].endswith("/projects/platform")
    assert (projects_root / "platform").is_dir()
    assert (projects_root / "platform" / "deliverables" / "implementation.md").is_file()

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_planner_run_creates_pending_plan_and_approval_queues_tasks(client: TestClient) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    plan = client.post(
        "/api/v1/project-plans/projects/futurecalc/pitch",
        json={
            "idea_title": "Pitch futuristic calculator",
            "idea_description": "Turn the idea into a bounded plan before building.",
        },
    ).json()
    adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Planned the calculator project.",'
            '"plan_summary":"Ship the calculator in two bounded steps.",'
            '"max_total_tasks":3,'
            '"planned_tasks":['
            '{"title":"Design calculator experience","description":"Define the UX direction.","type":"research","spawn_budget":0},'
            '{"title":"Build calculator shell","description":"Implement the initial app shell.","type":"feature","spawn_budget":1}'
            ']}'
        )
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    planner = client.post("/api/v1/agents", json={"name": "planner-idea", "role": "planner"}).json()

    work_response = client.post(f"/api/v1/agents/{planner['id']}/work")

    assert work_response.status_code == 200
    plans = client.get("/api/v1/project-plans", params={"project_id": "futurecalc"}).json()
    latest_plan = next(item for item in plans if item["id"] == plan["id"])
    assert latest_plan["status"] == "pending_approval"
    assert len(latest_plan["items"]) == 2

    approve_response = client.post(f"/api/v1/project-plans/{plan['id']}/approve")
    assert approve_response.status_code == 200
    approved_plan = approve_response.json()
    assert approved_plan["status"] == "approved"
    assert approved_plan["created_task_count"] == 2

    tasks = client.get("/api/v1/tasks").json()
    queued = [task for task in tasks if task["plan_id"] == plan["id"] and task["type"] != "idea"]
    assert len(queued) == 2

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_architect_idles_when_only_developer_feature_tasks_exist(client: TestClient) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    architect = client.post("/api/v1/agents", json={"name": "arch-idle", "role": "architect"}).json()
    developer = client.post("/api/v1/agents", json={"name": "dev-shell", "role": "developer"}).json()
    feature_task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Build calculator shell",
            "description": "Implement the initial app shell.",
            "type": "feature",
            "project_id": "futurecalc",
        },
    ).json()
    client.post(
        "/api/v1/project-plans/projects/futurecalc/pitch",
        json={
            "idea_title": "Future plan",
            "idea_description": "This should stay for the planner.",
        },
    )

    idle_response = client.post(f"/api/v1/agents/{architect['id']}/work")
    assert idle_response.status_code == 200
    assert idle_response.json()["outcome"] == "idle"

    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","artifact_paths":["shell.md"],"follow_up_tasks":[]}',
        files_to_create=["shell.md"],
    )
    developer_response = client.post(f"/api/v1/agents/{developer['id']}/work")

    assert developer_response.status_code == 200
    assert developer_response.json()["outcome"] == "completed"
    assert developer_response.json()["task_id"] == feature_task["id"]

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_all_agents_runs_each_agent_once_with_matching_tasks(client: TestClient) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    planner = client.post("/api/v1/agents", json={"name": "planner-batch", "role": "planner"}).json()
    developer = client.post("/api/v1/agents", json={"name": "developer-batch", "role": "developer"}).json()
    architect = client.post("/api/v1/agents", json={"name": "architect-batch", "role": "architect"}).json()
    client.post(
        "/api/v1/project-plans/projects/futurecalc/pitch",
        json={
            "idea_title": "Pitch futuristic calculator",
            "idea_description": "Turn the idea into a bounded plan before building.",
        },
    )
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Build calculator shell",
            "description": "Implement the initial app shell.",
            "type": "feature",
            "project_id": "futurecalc",
        },
    )
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Define spectacle-first product scope",
            "description": "Lock the feature envelope and explicit exclusions.",
            "type": "research",
            "project_id": "futurecalc",
        },
    )

    class FakeBatchAdapter:
        def __init__(self) -> None:
            self.workdirs: list[str | None] = []

        def run(self, *, prompt: str, workdir: Path | None = None, on_output=None) -> ExecutionResult:
            self.workdirs.append(str(workdir) if workdir is not None else None)
            if "Type: idea" in prompt:
                stdout = (
                    '{"summary":"planned","plan_summary":"bounded plan","max_total_tasks":2,'
                    '"planned_tasks":[{"title":"Build shell","description":"Implement shell.","type":"feature","spawn_budget":0}]}'
                )
            else:
                if workdir is not None:
                    target = workdir / "artifact.md"
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text("generated by fake executor\n")
                stdout = (
                    '{"summary":"done","memory_summary":"done","memory_content":"done",'
                    '"artifact_paths":["artifact.md"],"follow_up_tasks":[]}'
                )
            if on_output is not None:
                on_output("stdout", stdout)
            return ExecutionResult(
                stdout=stdout,
                stderr="",
                exit_code=0,
                command=["fake-batch-executor"],
            )

    adapter = FakeBatchAdapter()
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter

    response = client.post("/api/v1/agents/run-all")

    assert response.status_code == 200
    payload = response.json()
    assert payload["total_agents"] == 3
    assert payload["completed"] == 3
    assert payload["failed"] == 0
    assert payload["idle"] == 0
    assert {result["agent_id"] for result in payload["results"]} == {
        planner["id"],
        developer["id"],
        architect["id"],
    }

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_template_specialists_route_bugfix_to_refactor_specialist(client: TestClient) -> None:
    adapter = FakeExecutionAdapter(
        stdout='{"summary":"fixed","memory_summary":"fixed","memory_content":"fixed","artifact_paths":["fix.md"],"follow_up_tasks":[]}',
        files_to_create=["fix.md"],
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    prototype = client.post(
        "/api/v1/agents",
        json={
            "name": "prototype-bugfix",
            "role": "developer",
            "template_id": "developer_prototype_sprinter",
        },
    ).json()
    refactor = client.post(
        "/api/v1/agents",
        json={
            "name": "refactor-bugfix",
            "role": "developer",
            "template_id": "developer_refactor_specialist",
        },
    ).json()
    bugfix_task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Fix calculator buttons not responding",
            "description": "Resolve the broken click handling and regressions causing runtime errors.",
            "type": "bugfix",
            "project_id": "futurecalc",
        },
    ).json()

    prototype_response = client.post(f"/api/v1/agents/{prototype['id']}/work")
    refactor_response = client.post(f"/api/v1/agents/{refactor['id']}/work")

    assert prototype_response.status_code == 200
    assert prototype_response.json()["outcome"] == "idle"
    assert refactor_response.status_code == 200
    assert refactor_response.json()["outcome"] == "completed"
    assert refactor_response.json()["task_id"] == bugfix_task["id"]

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_all_prefers_specialist_developer_for_bugfix(client: TestClient) -> None:
    adapter = FakeExecutionAdapter(
        stdout='{"summary":"fixed","memory_summary":"fixed","memory_content":"fixed","artifact_paths":["fix.md"],"follow_up_tasks":[]}',
        files_to_create=["fix.md"],
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    prototype = client.post(
        "/api/v1/agents",
        json={
            "name": "prototype-batch-bugfix",
            "role": "developer",
            "template_id": "developer_prototype_sprinter",
        },
    ).json()
    refactor = client.post(
        "/api/v1/agents",
        json={
            "name": "refactor-batch-bugfix",
            "role": "developer",
            "template_id": "developer_refactor_specialist",
        },
    ).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Fix calculator buttons not responding",
            "description": "Resolve the broken click handling and regressions causing runtime errors.",
            "type": "bugfix",
            "project_id": "futurecalc",
        },
    )

    response = client.post("/api/v1/agents/run-all")

    assert response.status_code == 200
    payload = response.json()
    prototype_result = next(item for item in payload["results"] if item["agent_id"] == prototype["id"])
    refactor_result = next(item for item in payload["results"] if item["agent_id"] == refactor["id"])
    assert prototype_result["outcome"] == "idle"
    assert refactor_result["outcome"] == "completed"

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_plan_bounded_followups_respect_budget(client: TestClient) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    plan = client.post(
        "/api/v1/project-plans/projects/futurecalc/pitch",
        json={
            "idea_title": "Pitch futuristic calculator",
            "idea_description": "Bound the initial build plan.",
        },
    ).json()
    planner_adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Planned the calculator project.",'
            '"plan_summary":"Ship the calculator in two bounded steps.",'
            '"max_total_tasks":2,'
            '"planned_tasks":['
            '{"title":"Build calculator shell","description":"Implement the initial app shell.","type":"feature","spawn_budget":1}'
            ']}'
        )
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: planner_adapter
    planner = client.post("/api/v1/agents", json={"name": "planner-cap", "role": "planner"}).json()
    client.post(f"/api/v1/agents/{planner['id']}/work")
    client.post(f"/api/v1/project-plans/{plan['id']}/approve")

    developer_adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Implemented the calculator shell.",'
            '"memory_summary":"calculator shell",'
            '"memory_content":"Built the first shell.",'
            '"artifact_paths":["app.md"],'
            '"follow_up_tasks":['
            '{"title":"Add history","description":"Implement calculation history.","type":"feature","project_id":"futurecalc"},'
            '{"title":"Add themes","description":"Implement theme support.","type":"feature","project_id":"futurecalc"}'
            ']}'
        ),
        files_to_create=["app.md"],
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: developer_adapter
    developer = client.post("/api/v1/agents", json={"name": "dev-cap", "role": "developer"}).json()

    work_response = client.post(f"/api/v1/agents/{developer['id']}/work")

    assert work_response.status_code == 200
    payload = work_response.json()
    assert payload["outcome"] == "completed"
    assert len(payload["follow_up_task_ids"]) == 1

    approved_plan = next(
        item for item in client.get("/api/v1/project-plans", params={"project_id": "futurecalc"}).json()
        if item["id"] == plan["id"]
    )
    assert approved_plan["created_task_count"] == 2

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_agent_catalog_and_create_agent_with_template_and_skills(client: TestClient) -> None:
    catalog_response = client.get("/api/v1/agents/catalog")
    assert catalog_response.status_code == 200
    catalog = catalog_response.json()
    assert any(template["role"] == "developer" for template in catalog["templates"])
    testing_skill = next(skill for skill in catalog["skills"] if skill["id"] == "testing_strategy")
    assert testing_skill["path"].endswith("/agent_skills/testing_strategy/SKILL.md")
    assert "## Working Style" in testing_skill["instructions"]

    create_response = client.post(
        "/api/v1/agents",
        json={
            "name": "builder-pro",
            "role": "developer",
            "template_id": "developer_refactor_specialist",
            "instructions": "Prefer clean seams and leave migration notes.",
            "skill_ids": ["database_modeling", "testing_strategy"],
        },
    )

    assert create_response.status_code == 201
    agent = create_response.json()
    assert agent["template_id"] == "developer_refactor_specialist"
    assert agent["instructions"] == "Prefer clean seams and leave migration notes."
    assert agent["skill_ids"] == ["database_modeling", "testing_strategy"]


def test_run_agent_once_prompt_includes_template_skills_and_custom_instructions(client: TestClient) -> None:
    adapter = FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","follow_up_tasks":[]}'
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent = client.post(
        "/api/v1/agents",
        json={
            "name": "dev-instructions",
            "role": "developer",
            "template_id": "developer_senior_builder",
            "instructions": "Optimize for maintainability over speed.",
            "skill_ids": ["testing_strategy", "documentation_handoff"],
        },
    ).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Implement structured retries",
            "description": "Add explicit retry handling for failed agent work.",
            "type": "feature",
        },
    )

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    assert adapter.prompts
    prompt = adapter.prompts[0]
    assert "Senior Builder" in prompt
    assert "Optimize for maintainability over speed." in prompt
    assert "Path: " in prompt
    assert "Start from the riskiest behavior and verify that first." in prompt
    assert "Documentation Handoff" in prompt

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_returns_idle_when_queue_has_no_compatible_work(client: TestClient) -> None:
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"unused","follow_up_tasks":[]}'
    )
    agent = client.post("/api/v1/agents", json={"name": "reviewer-1", "role": "reviewer"}).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Build API",
            "description": "Developer-only work item.",
            "type": "feature",
        },
    )

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    assert response.json()["outcome"] == "idle"
    assert response.json()["task_run"] is None

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_marks_task_failed_on_executor_error(client: TestClient) -> None:
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout="",
        stderr="codex exec failed",
        exit_code=2,
    )
    agent = client.post("/api/v1/agents", json={"name": "tester-1", "role": "tester"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Validate release",
            "description": "Testing task that should fail.",
            "type": "review",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "failed"
    assert payload["task_id"] == task["id"]
    assert payload["task_run"]["status"] == "failed"
    assert payload["memory_id"] is None

    tasks = client.get("/api/v1/tasks").json()
    assert tasks[0]["status"] == "failed"

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_fails_project_task_when_no_artifacts_are_created(
    client: TestClient,
    projects_root,
) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "FutureCalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","follow_up_tasks":[]}'
    )
    agent = client.post("/api/v1/agents", json={"name": "dev-no-files", "role": "developer"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Create project files",
            "description": "Should create real files in the project workspace.",
            "type": "feature",
            "project_id": "FutureCalc",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "failed"
    assert payload["task_run"]["status"] == "failed"
    assert "without creating files" in payload["task_run"]["stderr"]
    assert (projects_root / "FutureCalc" / ".gitignore").is_file()
    assert (projects_root / "FutureCalc" / "scripts" / "START").is_file()
    assert not any(
        path.name not in {".gitkeep", ".gitignore", "README.md", ".digital-company", "scripts"}
        for path in (projects_root / "FutureCalc").iterdir()
    )

    updated_task = next(item for item in client.get("/api/v1/tasks").json() if item["id"] == task["id"])
    assert updated_task["status"] == "failed"

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_memory_search_and_worker_prompt_use_retrieved_context(client: TestClient) -> None:
    create_memory = client.post(
        "/api/v1/memory",
        json={
            "type": "decision",
            "summary": "Use Postgres task locking",
            "content": "Atomic row updates prevent two workers from claiming the same task.",
        },
    )
    assert create_memory.status_code == 201

    search_response = client.get(
        "/api/v1/memory/search",
        params={"query": "atomic task locking", "strategy": "hybrid"},
    )
    assert search_response.status_code == 200
    search_payload = search_response.json()
    assert len(search_payload) == 1
    assert search_payload[0]["summary"] == "Use Postgres task locking"
    assert search_payload[0]["combined_score"] > 0

    adapter = FakeExecutionAdapter(stdout='{"summary":"done","follow_up_tasks":[]}')
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent = client.post("/api/v1/agents", json={"name": "arch-1", "role": "architect"}).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Design task locking",
            "description": "Use prior knowledge about atomic task locking.",
            "type": "research",
        },
    )

    work_response = client.post(f"/api/v1/agents/{agent['id']}/work")
    assert work_response.status_code == 200
    assert adapter.prompts
    assert "Use Postgres task locking" in adapter.prompts[0]
    assert "score=" in adapter.prompts[0]
    assert "Repository root:" in adapter.prompts[0]

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_delete_agent_succeeds_only_without_history(client: TestClient) -> None:
    removable = client.post("/api/v1/agents", json={"name": "temp-agent", "role": "designer"}).json()
    assert removable["template_id"] == default_template_id_for_role(AgentRole.DESIGNER)

    delete_response = client.delete(f"/api/v1/agents/{removable['id']}")
    assert delete_response.status_code == 204

    historical = client.post("/api/v1/agents", json={"name": "historical-agent", "role": "developer"}).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Build initial flow",
            "description": "Create real project output.",
            "type": "feature",
        },
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","follow_up_tasks":[]}'
    )
    client.post(f"/api/v1/agents/{historical['id']}/work")

    blocked_delete = client.delete(f"/api/v1/agents/{historical['id']}")
    assert blocked_delete.status_code == 409
    assert "execution history" in blocked_delete.json()["detail"]

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_tolerates_stale_template_and_skill_ids(
    client: TestClient,
    session,
    projects_root,
) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Implemented bounded slice.",'
            '"memory_summary":"bounded slice",'
            '"memory_content":"Completed the scoped work.",'
            '"artifact_paths":["notes/result.md"],'
            '"follow_up_tasks":[]}'
        ),
        files_to_create=["notes/result.md"],
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent_payload = client.post("/api/v1/agents", json={"name": "stale-dev", "role": "developer"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Complete bounded slice",
            "description": "Finish the scoped implementation.",
            "type": "feature",
            "project_id": "futurecalc",
        },
    ).json()

    persisted_agent = session.get(Agent, uuid.UUID(agent_payload["id"]))
    assert persisted_agent is not None
    persisted_agent.template_id = "missing-template"
    persisted_agent.skill_ids = ["missing-skill", "testing_strategy"]
    session.commit()

    response = client.post(f"/api/v1/agents/{agent_payload['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "completed"
    assert payload["task_id"] == task["id"]
    assert "Skill: Testing Strategy" in adapter.prompts[0]
    assert "missing-skill" not in adapter.prompts[0]
    assert "Senior Builder" in adapter.prompts[0]
    assert (projects_root / "futurecalc" / "notes" / "result.md").is_file()

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_planner_invalid_structured_output_fails_instead_of_500(client: TestClient) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    client.post(
        "/api/v1/project-plans/projects/futurecalc/pitch",
        json={
            "idea_title": "Pitch futuristic calculator",
            "idea_description": "Turn the idea into a bounded plan before building.",
        },
    )
    adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Planner produced a draft.",'
            '"plan_summary":"Draft plan.",'
            '"max_total_tasks":2,'
            '"planned_tasks":['
            '{"title":"Define visual direction","description":"Prepare the design direction.","type":"design","spawn_budget":0}'
            ']}'
        )
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    planner = client.post("/api/v1/agents", json={"name": "planner-invalid", "role": "planner"}).json()

    response = client.post(f"/api/v1/agents/{planner['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "failed"
    assert payload["task_run"]["status"] == "failed"
    assert payload["task_run"]["result_payload"]["final_status"] == "failed"
    assert "did not match the required schema" in payload["task_run"]["result_payload"]["summary"]

    plans = client.get("/api/v1/project-plans", params={"project_id": "futurecalc"}).json()
    assert plans[0]["status"] == "draft"

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_unexpected_worker_exception_becomes_failed_run_instead_of_500(
    client: TestClient,
) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "futurecalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExplodingExecutionAdapter(
        message="planner adapter crashed"
    )
    agent = client.post("/api/v1/agents", json={"name": "planner-boom", "role": "planner"}).json()
    task = client.post(
        "/api/v1/project-plans/projects/futurecalc/pitch",
        json={
            "idea_title": "Pitch futuristic calculator",
            "idea_description": "Turn the idea into a bounded plan before building.",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "failed"
    assert payload["task_id"] == task["planning_task_id"]
    assert payload["task_run"]["status"] == "failed"
    assert "planner adapter crashed" in payload["task_run"]["stderr"]

    tasks = client.get("/api/v1/tasks").json()
    idea_task = next(item for item in tasks if item["id"] == task["planning_task_id"])
    assert idea_task["status"] == "failed"

    app.dependency_overrides.pop(execution_adapter_dependency, None)
