from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from app.api.dependencies import execution_adapter_dependency
from app.config import Settings
from app.main import app
from app.models.common import AgentRole
from app.services.execution import CodexCLIExecutionAdapter, ExecutionResult
from app.services.agent_catalog import default_template_id_for_role


class FakeExecutionAdapter:
    def __init__(
        self,
        *,
        stdout: str,
        stderr: str = "",
        exit_code: int = 0,
        files_to_create: list[str] | None = None,
    ):
        self._result = ExecutionResult(
            stdout=stdout,
            stderr=stderr,
            exit_code=exit_code,
            command=["fake-executor"],
        )
        self.prompts: list[str] = []
        self.workdirs: list[str | None] = []
        self._files_to_create = files_to_create or []

    def run(self, *, prompt: str, workdir: Path | None = None) -> ExecutionResult:
        self.prompts.append(prompt)
        self.workdirs.append(str(workdir) if workdir is not None else None)
        if workdir is not None:
            for relative_path in self._files_to_create:
                target = workdir / relative_path
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text("generated by fake executor\n")
        return self._result


def test_codex_cli_adapter_reports_missing_binary() -> None:
    adapter = CodexCLIExecutionAdapter(
        settings=Settings(codex_cli_command="definitely-missing-codex-binary")
    )

    result = adapter.run(prompt="test prompt")

    assert result.exit_code == 127
    assert "CODEX_EXECUTION_BACKEND=mock" in result.stderr


def test_run_agent_once_completes_task_and_creates_follow_ups(client: TestClient, projects_root) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "platform", "name": "Platform", "description": "Shared platform work."},
    )
    adapter = FakeExecutionAdapter(
        stdout=(
            '{"summary":"Implemented the first worker pass.",'
            '"memory_summary":"Worker completed feature",'
            '"memory_content":"Feature implementation landed and needs review.",'
            '"artifact_paths":["deliverables/implementation.md"],'
            '"follow_up_tasks":[{"title":"Review implementation",'
            '"description":"Perform a focused code review.",'
            '"type":"review","project_id":"platform"}]}'
        ),
        files_to_create=["deliverables/implementation.md"],
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent = client.post("/api/v1/agents", json={"name": "worker-dev", "role": "developer"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Ship worker runtime",
            "description": "Implement the first worker cycle.",
            "type": "feature",
            "project_id": "platform",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "completed"
    assert payload["task_id"] == task["id"]
    assert len(payload["follow_up_task_ids"]) == 1
    assert payload["task_run"]["status"] == "succeeded"
    assert payload["task_run"]["created_follow_up_tasks"] == 1

    task_response = client.get("/api/v1/tasks")
    tasks = task_response.json()
    assert {item["status"] for item in tasks} == {"done", "todo"}

    memory_response = client.get("/api/v1/memory")
    memories = memory_response.json()
    assert len(memories) == 1
    assert memories[0]["summary"] == "Worker completed feature"

    task_runs_response = client.get("/api/v1/task-runs")
    task_runs = task_runs_response.json()
    assert len(task_runs) == 1
    assert task_runs[0]["task_id"] == task["id"]
    assert adapter.prompts
    assert adapter.workdirs[0] is not None
    assert adapter.workdirs[0].endswith("/projects/platform")
    assert (projects_root / "platform").is_dir()
    assert (projects_root / "platform" / "deliverables" / "implementation.md").is_file()

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_agent_catalog_and_create_agent_with_template_and_skills(client: TestClient) -> None:
    catalog_response = client.get("/api/v1/agents/catalog")
    assert catalog_response.status_code == 200
    catalog = catalog_response.json()
    assert any(template["role"] == "developer" for template in catalog["templates"])
    testing_skill = next(skill for skill in catalog["skills"] if skill["id"] == "testing_strategy")
    assert testing_skill["path"].endswith("/agent_skills/testing_strategy/SKILL.md")
    assert "## Working Style" in testing_skill["instructions"]

    create_response = client.post(
        "/api/v1/agents",
        json={
            "name": "builder-pro",
            "role": "developer",
            "template_id": "developer_refactor_specialist",
            "instructions": "Prefer clean seams and leave migration notes.",
            "skill_ids": ["database_modeling", "testing_strategy"],
        },
    )

    assert create_response.status_code == 201
    agent = create_response.json()
    assert agent["template_id"] == "developer_refactor_specialist"
    assert agent["instructions"] == "Prefer clean seams and leave migration notes."
    assert agent["skill_ids"] == ["database_modeling", "testing_strategy"]


def test_run_agent_once_prompt_includes_template_skills_and_custom_instructions(client: TestClient) -> None:
    adapter = FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","follow_up_tasks":[]}'
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent = client.post(
        "/api/v1/agents",
        json={
            "name": "dev-instructions",
            "role": "developer",
            "template_id": "developer_senior_builder",
            "instructions": "Optimize for maintainability over speed.",
            "skill_ids": ["testing_strategy", "documentation_handoff"],
        },
    ).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Implement structured retries",
            "description": "Add explicit retry handling for failed agent work.",
            "type": "feature",
        },
    )

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    assert adapter.prompts
    prompt = adapter.prompts[0]
    assert "Senior Builder" in prompt
    assert "Optimize for maintainability over speed." in prompt
    assert "Path: " in prompt
    assert "Start from the riskiest behavior and verify that first." in prompt
    assert "Documentation Handoff" in prompt

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_returns_idle_when_queue_has_no_compatible_work(client: TestClient) -> None:
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"unused","follow_up_tasks":[]}'
    )
    agent = client.post("/api/v1/agents", json={"name": "reviewer-1", "role": "reviewer"}).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Build API",
            "description": "Developer-only work item.",
            "type": "feature",
        },
    )

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    assert response.json()["outcome"] == "idle"
    assert response.json()["task_run"] is None

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_marks_task_failed_on_executor_error(client: TestClient) -> None:
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout="",
        stderr="codex exec failed",
        exit_code=2,
    )
    agent = client.post("/api/v1/agents", json={"name": "tester-1", "role": "tester"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Validate release",
            "description": "Testing task that should fail.",
            "type": "review",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "failed"
    assert payload["task_id"] == task["id"]
    assert payload["task_run"]["status"] == "failed"
    assert payload["memory_id"] is None

    tasks = client.get("/api/v1/tasks").json()
    assert tasks[0]["status"] == "failed"

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_run_agent_once_fails_project_task_when_no_artifacts_are_created(
    client: TestClient,
    projects_root,
) -> None:
    client.post(
        "/api/v1/projects",
        json={"id": "FutureCalc", "name": "FutureCalc", "description": "Calculator project."},
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","follow_up_tasks":[]}'
    )
    agent = client.post("/api/v1/agents", json={"name": "dev-no-files", "role": "developer"}).json()
    task = client.post(
        "/api/v1/tasks",
        json={
            "title": "Create project files",
            "description": "Should create real files in the project workspace.",
            "type": "feature",
            "project_id": "FutureCalc",
        },
    ).json()

    response = client.post(f"/api/v1/agents/{agent['id']}/work")

    assert response.status_code == 200
    payload = response.json()
    assert payload["outcome"] == "failed"
    assert payload["task_run"]["status"] == "failed"
    assert "without creating files" in payload["task_run"]["stderr"]
    assert not any(path.name != ".gitkeep" for path in (projects_root / "FutureCalc").iterdir())

    updated_task = next(item for item in client.get("/api/v1/tasks").json() if item["id"] == task["id"])
    assert updated_task["status"] == "failed"

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_memory_search_and_worker_prompt_use_retrieved_context(client: TestClient) -> None:
    create_memory = client.post(
        "/api/v1/memory",
        json={
            "type": "decision",
            "summary": "Use Postgres task locking",
            "content": "Atomic row updates prevent two workers from claiming the same task.",
        },
    )
    assert create_memory.status_code == 201

    search_response = client.get(
        "/api/v1/memory/search",
        params={"query": "atomic task locking", "strategy": "hybrid"},
    )
    assert search_response.status_code == 200
    search_payload = search_response.json()
    assert len(search_payload) == 1
    assert search_payload[0]["summary"] == "Use Postgres task locking"
    assert search_payload[0]["combined_score"] > 0

    adapter = FakeExecutionAdapter(stdout='{"summary":"done","follow_up_tasks":[]}')
    app.dependency_overrides[execution_adapter_dependency] = lambda: adapter
    agent = client.post("/api/v1/agents", json={"name": "arch-1", "role": "architect"}).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Design task locking",
            "description": "Use prior knowledge about atomic task locking.",
            "type": "research",
        },
    )

    work_response = client.post(f"/api/v1/agents/{agent['id']}/work")
    assert work_response.status_code == 200
    assert adapter.prompts
    assert "Use Postgres task locking" in adapter.prompts[0]
    assert "score=" in adapter.prompts[0]
    assert "Repository root:" in adapter.prompts[0]

    app.dependency_overrides.pop(execution_adapter_dependency, None)


def test_delete_agent_succeeds_only_without_history(client: TestClient) -> None:
    removable = client.post("/api/v1/agents", json={"name": "temp-agent", "role": "designer"}).json()
    assert removable["template_id"] == default_template_id_for_role(AgentRole.DESIGNER)

    delete_response = client.delete(f"/api/v1/agents/{removable['id']}")
    assert delete_response.status_code == 204

    historical = client.post("/api/v1/agents", json={"name": "historical-agent", "role": "developer"}).json()
    client.post(
        "/api/v1/tasks",
        json={
            "title": "Build initial flow",
            "description": "Create real project output.",
            "type": "feature",
        },
    )
    app.dependency_overrides[execution_adapter_dependency] = lambda: FakeExecutionAdapter(
        stdout='{"summary":"done","memory_summary":"done","memory_content":"done","follow_up_tasks":[]}'
    )
    client.post(f"/api/v1/agents/{historical['id']}/work")

    blocked_delete = client.delete(f"/api/v1/agents/{historical['id']}")
    assert blocked_delete.status_code == 409
    assert "execution history" in blocked_delete.json()["detail"]

    app.dependency_overrides.pop(execution_adapter_dependency, None)
